# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Private Key Infrastructure

on:
  # pull_request:
  #   types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:

permissions:
  contents: read

env:
  # A workaround for long FQDN names provided by GitHub actions.
  FQDN: "localhost"

jobs:
  test_insecure_client:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
